artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/HenilBytes/Dataset/raw/main/PoultryDisease.zip
  local_data_file: artifacts/data_ingestion/PoultryDisease.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_bash_model_path: artifacts/prepare_base_model/updated_base_model.h5