artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/HenilBytes/Dataset/raw/main/PoultryDisease.zip
  local_data_file: artifacts/data_ingestion/PoultryDisease.zip
  unzip_dir: artifacts/data_ingestion
